*  1. 催眠可以帮你做什么？

催眠——可以快速戒烟；
催眠——可以快速减肥；
催眠——可以保健身体；
催眠——可以重塑性格；
催眠——可以快速减压；
催眠——可以快速治疗失眠；
催眠——可以快速提升自信；
催眠——可以快速治疗恐惧症；
催眠——可以快速调整偏食；
催眠——可以快速激发行动力；
催眠——可以快速提升影响力；
催眠——可以快速提升销售业绩；
催眠——可以改善人际关系；
催眠——可以有效掌控情绪；
......

催眠可以通过调整你潜意识深处的画面和程序，来改变人们的信念和行为习惯，重编你的生命脚本程序，快速删除或修改任何你不想要的行为，快速重建我们想要的积极正向的行为及习惯，获得我们想要的结果。

催眠，就是一门让我们改变自己命运，让自己更加幸福的科学。

*  2. 科学催眠三大步骤
这三个步骤会帮助你真真切切的提升你的能力和技术，在你成长为一个更称职的科学催眠师的道路上，通过提升你的富有想象力的精神力量，成功的创造美妙的具有很高接受性和听话度的深度催眠。

如果你想成为催眠别人专家，你必须相信你能催眠。你必须运用你的心智去创造你想要的结果，而不是让恐惧或自我怀疑，阻碍你催眠的成功。

只需遵循着简单的三个步骤：视觉化、确认和投射，你将会发现，他们会很好的为你和你的催眠对象工作，你拥有了自信，你作为催眠师的力量会暴涨。

** 视觉化

在你的心里浮现一个心理图像——你的催眠对象被你催眠后是如何的反应——然后想象看见它发生。
运用你的想象力想象出当你的催眠对象被催眠的时候，看上去是怎样的，感觉是怎样的。在你的心像里，你的催眠对象慢慢松散，柔软，放松，看到他们下颌放松，眼皮放松；看到他们的双手静静的平放在腿上。在你心中想象，你的催眠对象一旦接到你催眠她进入深度催眠的指令，就瞬间进入身体放松的低脑波状态。
在你的脑海中想象看见它发生，在你催眠催眠对象和确认催眠对象的状态之前，运用想象力，通过假装结果产生来增加视觉化，就像你真的看见它发生一样，100％的没有恐惧和疑虑，只是“就是这样的”。


** 确认
描述，用积极的方式描述，暗示和指令会引导催眠对象的主观意识去完全执行你的描述。在你催眠他之前，告诉你的催眠对象,在他身上将会发生什么；也悄悄地告诉自己，你在催眠催眠对象的时候期望让他做什么，给自己悄悄地确认，甚至让你心里的视觉化想象与现实链接起来。


** 投射
用你的心灵之眼看到你已经视觉化和确认的催眠反映，投射到催眠对象的潜意识心智中，自动创造催眠效果的完成。在你和催眠对象之间创造一个身体能量连接管道，通过这个引导，你会真实地感觉到你毫不费力地、轻松地帮助你的催眠对象进入到深度催眠状态。

运用你的投射力量来增加你对催眠对象暗示指令的能量，令他们除了让自己进入深度催眠状态以外，没有别的任何选择。

全身心的将你的心灵力量专注于这种设想上，然后投射它，就像你说过的，在心里看到的一样，作用于催眠对象身上让他进入深度催眠，一种深度的接受性极高的催眠状态。甚至想象你自己也进入了浅度的催眠状态，让你的注意力集中，就像激光束一样。

投射你的心里之前视觉化的场景，让你的催眠对象进入深度催眠状态，告诉你自己，并默默的给自己确认，当你在催眠他们的时候，你可以让他们进入深度的催眠状态，然后就简单地让它发生，只要简单的相信它能够发生就行。

想象你所投射的思想会增强你的专注，增强你的信念。所有的信念都是能量，积极的信念将会增加我们的能量；消极的信念会减少我们的能量，注意力不集中也会降低我们的能量，因而影响我的能力。不要分心，不要让任何一点点的怀疑爬进你的心里。
*  3. 催眠前谈话标准流程
** 第一步：简单介绍你的背景
当你的催眠对象进入你的办公室坐下来，并告诉你他希望通过催眠达到的目的之后，你最好先做一个自我介绍，告诉她一些你的背景信息，比如，你是怎么对催眠感兴趣的？
你需要让你的催眠对象认为你能够有能力用科学催眠治疗来帮助到他。
你的催眠对象对你了解的越多，那么他们就会越相信你具有就能够催眠他们并帮助他们的能力。

** 第二步：向你的催眠对象解释催眠是什么不是什么
从你出生到大概你 3 岁或 4 岁的时候，每件事情都被记录进我们的大脑，直接进入我们的潜意识。我们将这些情绪信息以单元或者比特为单位记录下来。爱，信任，安全、恐惧，误导，疼痛，困惑，等等。这些积极的和不积极的情绪可以伴随我们的一生，除非我们可以改变他们。

** 第三步：开始创建关于催眠威力的信念结构
催眠是一个非常好的方法来改变你的负面习惯、行为模式和负面情绪，因为所有的这些都在你的潜意识大脑中，而催眠可以帮助你重新编程你的潜意识心智并让它为你工作。
所有的催眠都是提高你的注意力专注度，催眠状态下暗示的力量比意识的建议大 9 倍。

** 第四步：谈论一些环境催眠
当你开车的时候，你被催眠了，因为当你的意识在做白日梦或者开小差的时候。你的潜意识在帮助你开车。你是否曾经驾驶你的车子，然后很奇怪你怎么到达你的目的地的？你被催眠了！每天，我们所有人都会被催眠很多次。

** 第五步：找出你们催眠对象的目标是什么

在你开始你的催眠治疗之前，你需要知道你的催眠对象的准确目的以及他希望通过催眠得到什么？
作为一个催眠师，可以从他的意识和潜意识层面来确认这些——他们通过催眠真正希望得到些什么，这样在你的催眠治疗中将能取得巨大的成功。
我跟他们说，如果催眠能够创造任何奇迹，那么你的目标是什么？写在一张纸上。
我要求我的催眠对象写在纸上，因为我发现让他写下来比我通过潜意识来获得这些信息更加得直接和容易。

** 第六步：为你的催眠对象写一份心理处方。
心里处方是我和他们谈话时和看到他们写下的愿望清单的时候创造出的自定义处方和建议。

** 第七步：测试催眠对象的听话度

问题 1：在你的一生中是否有个梦游，就是在完全睡着的状态中走动？
问题 2：如果你能想象你在喝一杯很酸很苦的柠檬汁或者在用吸管吸喝一杯用柠檬做的很酸很苦的果汁，你会不会发现你的嘴巴开始流口水呢？
问题 3：作为一个孩子，你会不会因为你父母给予你的表情受影响，或者他们所说的负面的话语，又或者是你父母对你说话时的声调而被影响的。
*  4. 与催眠对象达成协议
每个疗程开始之前都要与你的催眠对象达成一份协议。
如果你希望获得你的催眠对象，完全 100％ 的承诺，允许你催眠她，那么这份协议是非常重要的。
获得意识和潜意识的认同，可以增加催眠对象对于催眠的接受性，它能够创造出所有你和你的催眠对象之间最重要的默契，并且增加你在这次催眠治疗中的给予暗示的成功率和接受度。
每次催眠开始之前需要说这些：

我现在要通过催眠你来帮助你，我保证我会照顾好你。你是安全的，并且你想要我现在催眠你。我希望我要求你做的任何事，你都能立刻毫不思考的去完成，我将要催眠你并帮助你秒睡，克服妨碍你健康和幸福的一切障碍。
你是否明白并且同意让我现在来催眠你？

催眠对象必须要说“是”，或者点下头表示同意。
然后告诉你的催眠对象：

我们现在已经有了份协议，并且我将会开始催眠你秒睡，来帮助你克服你生活中的障碍，你将会立刻不假思索的去完成我要你做的任何事。
我现在将要催眠你，可以吗？

确保催眠对象第二次说“是”，或者点头确认。
这份在治疗师和催眠对象之间的催眠协议将会帮助你减低你的催眠对象对于你的抗拒心理。
你需要在每个疗程开始之前都做这个。
你不会失败，只要你的催眠对象不辜负他曾答应被催眠的协议，只要你懂得如何催眠他们。
*  5. “手贴脸”物理引导技术
  首先与你的催眠对象达成协议

让催眠对象坐在沙发上，然后你在脑海中回想这个引导脚本并且同时说：
        背靠在沙发上，让头靠在后面，现在把你的双手放在你的双腿上，一条腿上一只，让你的双脚不要交叉，放松并且平躺的放在地上。
        等一下，我将请你抬起你的左手，放在你的面前，距离你的脸大概30厘米的距离，我将会以你的手为注意力的焦点来催眠你。我们现在从提升你的注意力集中程度开始，睡眠就是提高你的注意力，放大你的专注。
        现在你的双手还是放在双腿上，我希望你能把注意力放到你的呼吸上，专注于你每一次吸气和每次呼气，当你注意到你的呼吸变得更深的时候，然后你深吸一口气，点头确认。

现在暂停一会儿，然后说：
        现在，专注于你的呼吸，当你发现你的呼吸改变的时候，当你深深地吸了一口气的时候，点头确认。

当催眠对象点头确认时说。
        非常好……你做得很棒。
        现在我希望你做三次缓慢的深呼吸，每次呼气的时候就想着放松你的身体和头脑，然后感觉到你的眼皮也开始放松。当你第三次呼气的时候，轻轻地闭上你的眼睛，并且放松你的眼皮。让你的眼皮变得更沉重……更放松……在你第三次呼气的时候闭上它们。

暂停，直到催眠对象闭上眼睛。
        现在保持你的眼睛闭上，运用你的想象力，想象你可以让你自己放松下来，继续保持你的眼睛闭着，直到我让你睁开。我希望你利用你孩子般创造性的想象力。当我数到 3，我希望你把你的左手抬到空中，放在你的脸前，掌心对着你的脸，距离大概 30 厘米左右。
        现在，在我催眠你之前，我们将要提高你的注意力，当我数到 3 的时候，让你的左手抬到你的脸前，保持你的眼睛仍然是闭着的。1……2……现在……3……现在把你的手抬到你的面前距离你的脸大概30厘米的地方，保持你的眼睛是闭着的。非常好……你做得很棒……现在继续闭着眼睛。就让那只手保持在那儿……你慢慢的放松你的另外一只手……放松……完全的放松下来。
        现在当你的左手放在你的面前的时候，我希望你能想象到我在你左手的手指之间放了小木块，然后立刻让你的手指分开……分开……让手指之间的距离变得更远……就像有小木块在你的手指之间，迫使你的手指张开，手指之间的距离变得更大。1……距离更远，张得更开……2……想象你的手指现在已经分得更开了……现在3……你左手的手指分得更开，你右手仍然是放松的，在你的大腿上仍然是放松的……现在想象我放了一块强大的磁铁在你左手的掌心中，同时在你的额头上也有一块强大的磁铁，当两块磁铁相对的时候，它们就会相互吸引，他们会吸在一起，现在立刻不经思考地让你的左手和手臂开始向你的脸靠近，被吸引得慢慢靠向你的脸……更近……更近……被吸引的靠近你的脸部。
        当你的手碰到你的脸的时候，简单的让它放松下来，就让它在你的脸上放松。被吸引着……拉扯着……推动者……更加的靠近……更加的靠近你的脸……现在磁铁的吸力提高了 10 倍……20倍……更加的靠近……更加的靠近……吸引着……拉扯着……越来越近。
        当你的手贴上你的脸的时候，让你的手在你的脸上放松。磁铁的吸力现在更加的强了。想象现在有一个橡皮筋绑住了你的头和手腕，并且现在这个橡皮筋在你的手靠近你的脸的同时变得越来越小……越来越小……越来越近……越来越近。

重复，直到你的催眠对象的手贴到脸和额头，并且放松下来为止。
        当你的手碰到你的脸的时候，你会让你的手停留在你的脸上，并且放松下来，直到我待会儿让你的手掉到你的腿上。

当催眠对象的手碰到他们的脸，你说：
        当我慢慢的从 3 数到 0，我希望你可以让你的头更加地向后靠去来放松你的颈部。
        3……头变得越来越沉，并且向后靠去，颈部的肌肉放松，手仍然待在你的脸上。2……更加的沉重，更加的放松，下颌的肌肉也放松下来，头部放松下来，颈部上的肌肉放松下来，手仍然停在你的脸上。
        1……你的颈部已经完全的放松，头低下来，越来越深，你的手仍然停留在你的脸上。0……头部完全放松下来，你的手仍然停留在你的脸上。
        当我碰到你的肩膀说“睡”的时候，我希望你能够马上让你停留在脸上的手立即放松下来，并且掉到你的腿上，就像布娃娃一样，一个松软无力的布娃娃一样。当你的手掉了你的大腿上的时候，你会立刻掉进深度的催眠状态，并且你的身体会立刻的更深地放松下来。

重复，直到确认你的催眠对象明白并且接受将要发生的一切。
        但我碰到你的肩膀，你的手会立刻掉到你的腿上，你的颈部的肌肉会放松，你的头会马上低得更低，更加的放松，然后你会进入深度的催眠放松状态，你立刻被深度催眠了。

你现在应该触碰并向下压你的催眠对象的肩膀，然后说：“睡”；同时在你说“睡”的时候要用力的压你的催眠对象的肩膀一下。如果催眠对象接受你的引导，他们的手会马上掉到他们的大腿上，他们的头也会低下来，同时他们的颈部也放松下来，他们会立刻进入深度的催眠状态。
        现在手掉下来！睡！5……4……3……2……1……现在，深度的催眠状态，每一块肌肉，每一根神经，每一根纤维和每一个组织都已经完全的放松下来……更深的放松……松软而无力……每一次呼吸的时候都会把你带入越来越深沉，越来越放松的催眠状态。



重点强调
当你说“睡”的时候，不要在说完之后留下停顿空隙，你必须继续说话，并且鼓励催眠对象更加的放松。
当你说完“睡”，接下来马上说这些：
        5……4……3……2……1……现在，深度催眠状态……每一块肌肉，每一根神经，每一根纤维和每一个组织都完全的放松……更深的放松……松软而无力，就像一个布娃娃。现在每一次呼气都会带你进入越来越深越来越平和的催眠状态。


给你的建议
练习上面的话语，让这些话能够很自然地从你的口中说出来，就像一条平滑流淌的小溪，光滑的鹅卵石。如果你不练习，你会发现“睡”这个字会影响到你的注意力，就像对催眠对象的影响一样，让你在一瞬间不知道要说什么，甚至忘记你接下来要说什么。
如果你在说完“睡”之后不说上面的话，你会发现你的催眠对象将会开始从催眠状态中苏醒，在某种程度上，这是一种心理机能的自我保护。
*  6. “手轻手重”物理引导技术
  你现在准备开始手轻手重物理引导技术，接下来是所有指定的脚本。换了用用视觉化确认投射的力量。
一开始你让你的催眠对象坐在沙发上或者椅子上，双脚平放在地板上，双手放在腿上。

与村民对象达成协议。
在你进行每个引导之前，确保你获得他愿意被催眠的协议。

手轻手重，引导脚本。
重复一下的脚本公式。
背靠在沙发上，逃往后靠，双手放在腿上，掌心向下，一条腿上一只双腿不要交叉，平放在地板上，让他们休息，非常的放松。我们现在将开始聚焦你的注意力和专注力，催眠就是放大专注力。
你的双手放在你的双腿上，我希望你聚焦你的注意力，关注你的呼吸，专注在你每次的呼吸气和呼气。当你注意到你的呼吸变得深沉，你就做一个深呼吸，然后点头确认。

暂停一下说。
现在专注你的呼吸，然后点头确认。

当催眠对象点头确认，你就说。
非常好，你做的非常好。
现在我希望你缓慢地做三次深呼吸，每次呼气的时候就想象你全身心的放松，你感觉到你的眼皮放松了，让你的眼皮变得更沉重，更放松，当你第三次呼吸的时候闭上你的眼睛。

暂停，直到他闭上眼睛。
现在闭上你的眼睛，你能够让你自己放松，运用你的想象力，继续保持你的眼睛闭着，直到我让你睁开。我希望你利用你孩子般创造性的想象力，现在当我数到三，我希望你举起你的双手，手臂伸直，手指指向前方。一，二，三，举起你的双手向前伸直，手指指向前方，把你的手掌朝下。像天空，手指伸直，你做得非常完美。
当我数到三想象甚至假装看见，我放了一个钢球一样的重物在你左手的手心，重20斤。我希望你让你的手立刻慢慢的下落，无需思考，掉到你的腿上。当你的手碰到你的腿，你的手臂和手立刻完全的放松，一。三，左手越来越重，感觉干球在你的手掌中。中十二十斤晚上钓，晚上呀，现在仿佛是两个钢球中20，40斤在你的左手，你的手臂和手非常的沉重。
让你的右手和手臂感觉到很轻，好像有一个氢气球，既然你的右手腕拉伸着你的右手和手臂升到空中越来越高，越来越轻，晚上升越来越高，轻如羽毛。
左手和手臂往下掉往下落，直到掉到腿上，同时你的右手和手臂一路向上举起巨大，直到手指指向天空。左手越来越重越来越重，往下掉，直到碰到你的腿，然后彻底放松下来，同时你的呼吸开始变得越来越深沉，每次呼气的时候想象着放松你的身体和头脑。你的右手和手臂一路向上，举到空中，仿佛有一打12的氢气球机在你的右手手腕上，你的右手，像羽毛一样，非常的轻，越来越轻，轻如羽毛，你的左手和手臂掉下来，掉到你的腿上。你的右手伸得越来越高，完全的身高手指指向天空，现在更加亲五倍以上，越来越清，670倍，像羽毛一样。八倍九倍，如果你需要的话，还可以十倍或者更多。

重复这些暗示，直到催眠对象的右手完全指向天，空中，左手完全的放松的落在腿上。
现在你可以做一个不接触或者接触身体的引导。

小金手中不接触身体的引导，方法。
如果你想瞬间立刻催眠催眠对象，说。
但我从三数到零，我说睡，你伸出的手会立刻放松，并立刻掉到你的腿上，放松，没有意思了呀，力量像一个布娃娃一样。
当我数到零，并且说睡，你的手，立刻跳到你的腿上，你家立刻进入到非常奇妙的深度催眠放松的状态。
三，二，一，零，手掉下来，睡。

手轻手重，接触身体的营养方法。
当你的催眠对象左手放到腿上，而右手举到空中时，对你的催眠对象说。
当我触碰到您的肩膀，并且说放松你的手会立刻跳到你的腿上，你的头会垂下来，你会立刻放松你颈部的肌肉，你立刻进入深度催眠放松状态。
当我触碰你的肩膀，并且说睡，你会立刻身体放松，你的是整个身体变得松软无力和放松。而每次呼气都送你到更深的休息放松状态。当我触碰你的肩膀，让你的手臂立刻掉在你的腿上，想象它让它发生。

现在走向你的催眠对象，往下压他的肩膀说。
下午和手臂掉下来，现在，睡。
放松你的颈部肌肉，放松你的下颌肌肉，进入一种更深的放松状态。
*  7. “旋转手”快速物理引导技术
  这种引导技术是混乱技术和身体物理运动和快速指令的结合。它非常有效，但要求你在下指令时必须有权威感。

让你的催眠对象坐在椅子上，在你引导前和他达成协议。
一边展示给他们双手怎么操作，一边引导他们：
当我数到三，我希望你开始旋转你的双手，向着自己的方向，互相围绕，当我说“反转”，你反转你的双手，互相围绕，向远离你的方向。每次我说“反转”，立刻切换方向旋转你的双手，当我要求你快速转动时，听到“快”这个词，你不需要思考，立刻转动你的手，越来越快。
当我说“睡”，请你让你的双手掉下来，到你的腿上，你家立刻进入深度催眠放松状态，同时你整个身体和头脑都立刻掉入平静的状态，你会越来越深的放松下来。

当你开始解释你的引导，同时用你的双手示范动作，你会发现你的催眠对象反映反射你的动作，在你完成解释之前，这是一个听话度高的催眠对象，跟随引导的迹象。
重复指令，确保催眠对象理解我们期待他们要做的。
当我请你把手举到你面前，手指互相指着，然后我请你向内转动你的双手，互相围绕，你会立刻转动，当我说“快”，你就要更快的转动，每次我说“反转”，你就反转动作，让我碰到你的肩膀，然后说“睡”，你就立刻进入深度催眠状态，——你懂我的意思吗？
好，让我们开始……

现在，你说：
当我数到三，你开始转动你的双手，一……二……三……开始转动。一圈又一圈……看着并专注在你的双手……转动……转动……快……再快……现在反转……转动……继续转动……快……再快……反转……更快，更圆……反转反方向……更快，更圆……更快……更快……反转……反转……反转。

触碰，坚定的下压他的双肩，同时下达一个威严的指令。
手放下，睡深深的放松。
这个技巧的关键是在催眠对象反转时，你让催眠对象更快更快，反转，更快更快，反转，反转，反转，反转，更快，反转，反转。

另一种示范是，一只手触碰催眠对象的前额，轻推她的头后部，同时下指令：
睡，你已经被深深的催眠了。
这是超载快速催眠引导，创造出混乱和非常棒的效果。

*  8. “手拉一起”快速物理引导技术
  这是一种功能强大效果非常好的引导技术，特别是对于视觉型的证明对象。

让催眠对象坐在椅子上面对你，告诉他伸直他的双手，伸向前面，手心相对。他们的手和手臂平伸向前方展清香，对他们的手指笔直地伸向前方，告诉催眠对象，你将要瞬间催眠他们，并得到他们的催眠认可，像前面提到的那样达成协议。
告诉催眠对象，做三次深呼吸，在第三次呼气的时候，闭上他们的眼睛，当催眠对象，闭上他们的眼睛。告诉他们去想象有一个大磁铁，在他们的手双手之间有非常强大的吸引力，想象他们的双手护越来越互相靠近越来越近。
你可以把你的拳头放在他们双手之间，帮助他们完成想象，不断地重复暗示，他们的手越来越靠近越来越近。
然后说你拉他的双手，他就立刻被催眠，他的双手一旦碰在一起，快速的拉她的手，在一起大喊一个字睡，当你朝你的方向拉他的双手，黑名单下，就会倒在椅子里。然后说，你现在深深的被催眠了，随着每次呼气，你进入越来越深的放松状态。

做引导前，先让催眠对象坐到椅子上，双手放在腿上，双脚平放在地板上现在我要深度催眠你，我要你做的一切你都要照做，并且不用去思考，你明白吗？催眠对象说，是的。你说啊，非常好，我们现在开始。我希望你坐在椅子上，你的双手轻轻放在你的腿上，现在我要你看着我，我希望你举起你的双手放在你的面前，分开60厘米的距离，掌心相对，就像我做的一样好，现在我把拳头放在你的双手中间，我想让你看着我的拳头，立刻专注于我的拳头，并且当你专注的看着我的拳头时，把你的注意力聚焦在你的呼吸上，深吸一口气，点头确认一下。下一行。暂停，直到催眠对象点头确认，非常好，现在你一边看着我，放在你双手间的拳头，一边做三次深呼吸，吸气，吐气看着我的拳头，我的拳头在你的双手中间，在你呼气的时候，体会你放松的感觉，当你第三次呼气时，闭上眼睛，依然让注意力专注于我放在你面前的拳头，现在想象一下，我的拳头是一个强大的词典，吸引着你的双手越来越近，想要拉在一起，吸力越来越大，越来越大，当我碰到你的双手同时说睡，你的身体将立刻放松，你将进入深度催眠状态，你的双手越来越近，好像有一个橡皮筋在你的手上，距离越来越小，越来越靠近西。得越来越近，几乎想要靠在一起，当我轻拉你的手，你的身体会垂下来，你立刻放松，进入深度的催眠状态，头低下来，你的双手和腿以及全身会立刻放松，不断的重复这些暗示，直到村民对象的双手准备互相接触，单双手距离五厘米时，把你的双手放在村民对象的手外边，然后突然向内拉，轻微震一下，下达指令，岁向下拉催眠对象的手，同时说，现在你身体的每一块肌肉，每一根神经。每一根纤维和每一个组织完全放松下来，进入越来越深的放松状态，每次呼气的时候，放松的感觉就会从头顶一直蔓延到脚趾头，每次呼气的时候，自己进入更深的放松状态，更深更深的宁静，放松状态，正如任何的快速引导，这是非常重要的，你下指令的时机非常重要，当你说睡，你继续鼓励他们进入更放松更深入的放松状态，如果你留下了空隙缺口，哪怕是几秒钟的催眠对象，可能会很快从催眠状态中逃离出来，在村民对象给反馈的时候，他们都表示用一种震撼动作引导，而不是简单的放松词汇，让他们放松更深，完全不一样的感受。现在催眠对象处在催眠状态，你可以用任何一个前面章节里讲过的加深技术做加深。

*  9. 看着我的眼睛 瞬间物理引导技术
  告诉你，催眠对象，你将要催眠他，让她坐在椅子上，双手放在腿上，跟你的催眠对象达成协议说我在这里将要做的就是我要立刻催眠你，等一下我会请你闭上你的眼睛，当你睁闭上眼睛，我希望你去想象你的心灵，放松去想，放松你的心灵和身体，并允许我催眠你进入很深的催眠状态，当我让你看我的眼睛，同时我说睡，你会进入非常深的放松和宁静的催眠状态，现在你必须允许我催眠你吗？村民对象必须说是的，然后你对催眠对象说好，非常棒，让我们开始现在双手放在腿上，一条腿上，一只掌心向下，现在看着你放在腿上休息的双手想象，放松你的双手变得松软无力和放松，现在聚焦你的注意力，在你的呼吸上，慢速的长长的，深吸一口气，屏气5分5秒钟，当你呼气的时候，让你的手变得更放松，限贷，放松你眼皮的肌肉，你做的很完美，现在再次深吸一口气，屏气五秒钟，当你呼气时，我希望你只是闭上眼睛，现在闭上眼睛，放松你的眼皮，想象你的双手变得更加放松温暖，我现在就要催眠你，等一下我将触碰你的肩膀，当我碰到你。 你的肩膀，当我碰到你的肩膀，你就睁开你的双眼，然后看着我的眼睛，当你看到我的眼睛，并听到我说睡，你会立刻闭上眼睛，头迅速沉下去，你的身体立刻放松，你将进入非常深的催眠状态，现在触碰村民对象的肩膀，并告诉他，看着你的眼睛一旦当他睁开双眼，你只是他的眼睛，你的脸迅速贴近到只有几厘米的距离，同时说睡在同一时间，已经坚定的态度，吓一下他左边或者右边的肩膀说，闭上眼睛，头和身体完全放松，进入深沉的催眠状态，催眠对象的眼睛将会关闭，他的身体立刻掉进深深的放松状态，现在你继续重复引导过程，现在睁开你的眼，看着我的眼睛，催眠对象开始。 睁开他的眼睛来看你，你就在他脸前几厘米的地方看着她，同时跟你说睡下呀，你催眠对象的肩膀并下指令，放松眼睛，闭上头低下来，你的全身变得松软无力，放松，从头顶到脚趾，全身的每一个部位都完全放松，同时你注意到这种放松是多么美妙的，感觉，你的下额肌肉放松，嘴巴微微张开，每当我说放松这个词，你的全身都会变得松软无力放松你全身都会进入非常深的宁静的状态，现在你的村民对象已经被催眠了，像一件事，你需要去按照之前讲过的，非常多的加深技术来对为催眠对象做加深。
*  10. 吸气和呼气快速引导技术
*  11. “三次握手法”物理引导技术
*  12. “锁手法”快速催眠引导技术
*  13. “从对象手中抽手”快速引导技术
*  14. “睁眼闭眼”快速引导技术
*  15. “四次击掌”震撼引导技术
*  16. 秘密瞬间催眠引导技术
*  17. 科学催眠加深技术“工具箱”
*  18. 催眠戒烟
*  19. 催眠减肥
*  20. 恐惧与恐惧症
*  21. 视觉意向技术
*  22. 决绝睡眠问题
*  23. 团体催眠戒烟
*  24. 制作催眠治疗CD
*  25. 团队催眠动力培训会
*  26. 年龄回溯技术
*  27. 各种问题的催眠脚本
*  28. 自我催眠震撼物理引导技术
